import test, { describe } from 'node:test';
import { expect } from './expect.ts';
import { is } from '../sources/is.ts';

describe('is', () => {
  test('boolean()', () => {
    expect(is.boolean(false)).toBeTruthy();
    expect(is.boolean(true)).toBeTruthy();
    expect(is.boolean(new Boolean())).toBeTruthy();
    expect(is.boolean(0)).toBeFalsy();
    expect(is.boolean(1)).toBeFalsy();
    expect(is.boolean(new Number())).toBeFalsy();
    expect(is.boolean('')).toBeFalsy();
    expect(is.boolean('test')).toBeFalsy();
    expect(is.boolean(new String('Test'))).toBeFalsy();
    expect(is.boolean([])).toBeFalsy();
    expect(is.boolean([1, 2, 3])).toBeFalsy();
    expect(is.boolean(new Array())).toBeFalsy();
    expect(is.boolean({})).toBeFalsy();
    expect(is.boolean({ key: 'value' })).toBeFalsy();
    expect(is.boolean(new Object())).toBeFalsy();
    expect(is.boolean(() => {})).toBeFalsy();
    expect(is.boolean(function () {})).toBeFalsy();
    expect(is.boolean(new Function())).toBeFalsy();
    expect(is.boolean(undefined)).toBeFalsy();
    expect(is.boolean(null)).toBeFalsy();
    expect(is.boolean(NaN)).toBeFalsy();
    expect(is.boolean(new Number(NaN))).toBeFalsy();
    expect(is.boolean(Infinity)).toBeFalsy();
    expect(is.boolean(-Infinity)).toBeFalsy();
    expect(is.boolean(new Number(Infinity))).toBeFalsy();
  });
  test('number()', () => {
    expect(is.number(false)).toBeFalsy();
    expect(is.number(true)).toBeFalsy();
    expect(is.number(new Boolean())).toBeFalsy();
    expect(is.number(0)).toBeTruthy();
    expect(is.number(1)).toBeTruthy();
    expect(is.number(new Number())).toBeTruthy();
    expect(is.number('')).toBeFalsy();
    expect(is.number('test')).toBeFalsy();
    expect(is.number(new String('Test'))).toBeFalsy();
    expect(is.number([])).toBeFalsy();
    expect(is.number([1, 2, 3])).toBeFalsy();
    expect(is.number(new Array())).toBeFalsy();
    expect(is.number({})).toBeFalsy();
    expect(is.number({ key: 'value' })).toBeFalsy();
    expect(is.number(new Object())).toBeFalsy();
    expect(is.number(() => {})).toBeFalsy();
    expect(is.number(function () {})).toBeFalsy();
    expect(is.number(new Function())).toBeFalsy();
    expect(is.number(undefined)).toBeFalsy();
    expect(is.number(null)).toBeFalsy();
    expect(is.number(NaN)).toBeFalsy();
    expect(is.number(new Number(NaN))).toBeFalsy();
    expect(is.number(Infinity)).toBeFalsy();
    expect(is.number(-Infinity)).toBeFalsy();
    expect(is.number(new Number(Infinity))).toBeFalsy();
  });
  test('string()', () => {
    expect(is.string(false)).toBeFalsy();
    expect(is.string(true)).toBeFalsy();
    expect(is.string(new Boolean())).toBeFalsy();
    expect(is.string(0)).toBeFalsy();
    expect(is.string(1)).toBeFalsy();
    expect(is.string(new Number())).toBeFalsy();
    expect(is.string('')).toBeTruthy();
    expect(is.string('test')).toBeTruthy();
    expect(is.string(new String('Test'))).toBeTruthy();
    expect(is.string([])).toBeFalsy();
    expect(is.string([1, 2, 3])).toBeFalsy();
    expect(is.string(new Array())).toBeFalsy();
    expect(is.string({})).toBeFalsy();
    expect(is.string({ key: 'value' })).toBeFalsy();
    expect(is.string(new Object())).toBeFalsy();
    expect(is.string(() => {})).toBeFalsy();
    expect(is.string(function () {})).toBeFalsy();
    expect(is.string(new Function())).toBeFalsy();
    expect(is.string(undefined)).toBeFalsy();
    expect(is.string(null)).toBeFalsy();
    expect(is.string(NaN)).toBeFalsy();
    expect(is.string(new Number(NaN))).toBeFalsy();
    expect(is.string(Infinity)).toBeFalsy();
    expect(is.string(-Infinity)).toBeFalsy();
    expect(is.string(new Number(Infinity))).toBeFalsy();
  });
  test('array()', () => {
    expect(is.array(false)).toBeFalsy();
    expect(is.array(true)).toBeFalsy();
    expect(is.array(new Boolean())).toBeFalsy();
    expect(is.array(0)).toBeFalsy();
    expect(is.array(1)).toBeFalsy();
    expect(is.array(new Number())).toBeFalsy();
    expect(is.array('')).toBeFalsy();
    expect(is.array('test')).toBeFalsy();
    expect(is.array(new String('Test'))).toBeFalsy();
    expect(is.array([])).toBeTruthy();
    expect(is.array([1, 2, 3])).toBeTruthy();
    expect(is.array(new Array())).toBeTruthy();
    expect(is.array({})).toBeFalsy();
    expect(is.array({ key: 'value' })).toBeFalsy();
    expect(is.array(new Object())).toBeFalsy();
    expect(is.array(() => {})).toBeFalsy();
    expect(is.array(function () {})).toBeFalsy();
    expect(is.array(new Function())).toBeFalsy();
    expect(is.array(undefined)).toBeFalsy();
    expect(is.array(null)).toBeFalsy();
    expect(is.array(NaN)).toBeFalsy();
    expect(is.array(new Number(NaN))).toBeFalsy();
    expect(is.array(Infinity)).toBeFalsy();
    expect(is.array(-Infinity)).toBeFalsy();
    expect(is.array(new Number(Infinity))).toBeFalsy();
  });
  test('object()', () => {
    expect(is.object(false)).toBeFalsy();
    expect(is.object(true)).toBeFalsy();
    expect(is.object(new Boolean())).toBeFalsy();
    expect(is.object(0)).toBeFalsy();
    expect(is.object(1)).toBeFalsy();
    expect(is.object(new Number())).toBeFalsy();
    expect(is.object('')).toBeFalsy();
    expect(is.object('test')).toBeFalsy();
    expect(is.object(new String('Test'))).toBeFalsy();
    expect(is.object([])).toBeFalsy();
    expect(is.object([1, 2, 3])).toBeFalsy();
    expect(is.object(new Array())).toBeFalsy();
    expect(is.object({})).toBeTruthy();
    expect(is.object({ key: 'value' })).toBeTruthy();
    expect(is.object(new Object())).toBeTruthy();
    expect(is.object(() => {})).toBeFalsy();
    expect(is.object(function () {})).toBeFalsy();
    expect(is.object(new Function())).toBeFalsy();
    expect(is.object(undefined)).toBeFalsy();
    expect(is.object(null)).toBeFalsy();
    expect(is.object(NaN)).toBeFalsy();
    expect(is.object(new Number(NaN))).toBeFalsy();
    expect(is.object(Infinity)).toBeFalsy();
    expect(is.object(-Infinity)).toBeFalsy();
    expect(is.object(new Number(Infinity))).toBeFalsy();
  });
  test('function()', () => {
    expect(is.function(false)).toBeFalsy();
    expect(is.function(true)).toBeFalsy();
    expect(is.function(new Boolean())).toBeFalsy();
    expect(is.function(0)).toBeFalsy();
    expect(is.function(1)).toBeFalsy();
    expect(is.function(new Number())).toBeFalsy();
    expect(is.function('')).toBeFalsy();
    expect(is.function('test')).toBeFalsy();
    expect(is.function(new String('Test'))).toBeFalsy();
    expect(is.function([])).toBeFalsy();
    expect(is.function([1, 2, 3])).toBeFalsy();
    expect(is.function(new Array())).toBeFalsy();
    expect(is.function({})).toBeFalsy();
    expect(is.function({ key: 'value' })).toBeFalsy();
    expect(is.function(new Object())).toBeFalsy();
    expect(is.function(() => {})).toBeTruthy();
    expect(is.function(function () {})).toBeTruthy();
    expect(is.function(new Function())).toBeTruthy();
    expect(is.function(undefined)).toBeFalsy();
    expect(is.function(null)).toBeFalsy();
    expect(is.function(NaN)).toBeFalsy();
    expect(is.function(new Number(NaN))).toBeFalsy();
    expect(is.function(Infinity)).toBeFalsy();
    expect(is.function(-Infinity)).toBeFalsy();
    expect(is.function(new Number(Infinity))).toBeFalsy();
  });

  test('undefined()', () => {
    expect(is.undefined(false)).toBeFalsy();
    expect(is.undefined(true)).toBeFalsy();
    expect(is.undefined(new Boolean())).toBeFalsy();
    expect(is.undefined(0)).toBeFalsy();
    expect(is.undefined(1)).toBeFalsy();
    expect(is.undefined(new Number())).toBeFalsy();
    expect(is.undefined('')).toBeFalsy();
    expect(is.undefined('test')).toBeFalsy();
    expect(is.undefined(new String('Test'))).toBeFalsy();
    expect(is.undefined([])).toBeFalsy();
    expect(is.undefined([1, 2, 3])).toBeFalsy();
    expect(is.undefined(new Array())).toBeFalsy();
    expect(is.undefined({})).toBeFalsy();
    expect(is.undefined({ key: 'value' })).toBeFalsy();
    expect(is.undefined(new Object())).toBeFalsy();
    expect(is.undefined(() => {})).toBeFalsy();
    expect(is.undefined(function () {})).toBeFalsy();
    expect(is.undefined(new Function())).toBeFalsy();
    expect(is.undefined(undefined)).toBeTruthy();
    expect(is.undefined(null)).toBeFalsy();
    expect(is.undefined(NaN)).toBeFalsy();
    expect(is.undefined(new Number(NaN))).toBeFalsy();
    expect(is.undefined(Infinity)).toBeFalsy();
    expect(is.undefined(-Infinity)).toBeFalsy();
    expect(is.undefined(new Number(Infinity))).toBeFalsy();
  });
  test('null()', () => {
    expect(is.null(false)).toBeFalsy();
    expect(is.null(true)).toBeFalsy();
    expect(is.null(new Boolean())).toBeFalsy();
    expect(is.null(0)).toBeFalsy();
    expect(is.null(1)).toBeFalsy();
    expect(is.null(new Number())).toBeFalsy();
    expect(is.null('')).toBeFalsy();
    expect(is.null('test')).toBeFalsy();
    expect(is.null(new String('Test'))).toBeFalsy();
    expect(is.null([])).toBeFalsy();
    expect(is.null([1, 2, 3])).toBeFalsy();
    expect(is.null(new Array())).toBeFalsy();
    expect(is.null({})).toBeFalsy();
    expect(is.null({ key: 'value' })).toBeFalsy();
    expect(is.null(new Object())).toBeFalsy();
    expect(is.null(() => {})).toBeFalsy();
    expect(is.null(function () {})).toBeFalsy();
    expect(is.null(new Function())).toBeFalsy();
    expect(is.null(undefined)).toBeFalsy();
    expect(is.null(null)).toBeTruthy();
    expect(is.null(NaN)).toBeFalsy();
    expect(is.null(new Number(NaN))).toBeFalsy();
    expect(is.null(Infinity)).toBeFalsy();
    expect(is.null(-Infinity)).toBeFalsy();
    expect(is.null(new Number(Infinity))).toBeFalsy();
  });
  test('NaN()', () => {
    expect(is.NaN(false)).toBeFalsy();
    expect(is.NaN(true)).toBeFalsy();
    expect(is.NaN(new Boolean())).toBeFalsy();
    expect(is.NaN(0)).toBeFalsy();
    expect(is.NaN(1)).toBeFalsy();
    expect(is.NaN(new Number())).toBeFalsy();
    expect(is.NaN('')).toBeFalsy();
    expect(is.NaN('test')).toBeFalsy();
    expect(is.NaN(new String('Test'))).toBeFalsy();
    expect(is.NaN([])).toBeFalsy();
    expect(is.NaN([1, 2, 3])).toBeFalsy();
    expect(is.NaN(new Array())).toBeFalsy();
    expect(is.NaN({})).toBeFalsy();
    expect(is.NaN({ key: 'value' })).toBeFalsy();
    expect(is.NaN(new Object())).toBeFalsy();
    expect(is.NaN(() => {})).toBeFalsy();
    expect(is.NaN(function () {})).toBeFalsy();
    expect(is.NaN(new Function())).toBeFalsy();
    expect(is.NaN(undefined)).toBeFalsy();
    expect(is.NaN(null)).toBeFalsy();
    expect(is.NaN(NaN)).toBeTruthy();
    expect(is.NaN(new Number(NaN))).toBeTruthy();
    expect(is.NaN(Infinity)).toBeFalsy();
    expect(is.NaN(-Infinity)).toBeFalsy();
    expect(is.NaN(new Number(Infinity))).toBeFalsy();
  });
  test('Infinity()', () => {
    expect(is.Infinity(false)).toBeFalsy();
    expect(is.Infinity(true)).toBeFalsy();
    expect(is.Infinity(new Boolean())).toBeFalsy();
    expect(is.Infinity(0)).toBeFalsy();
    expect(is.Infinity(1)).toBeFalsy();
    expect(is.Infinity(new Number())).toBeFalsy();
    expect(is.Infinity('')).toBeFalsy();
    expect(is.Infinity('test')).toBeFalsy();
    expect(is.Infinity(new String('Test'))).toBeFalsy();
    expect(is.Infinity([])).toBeFalsy();
    expect(is.Infinity([1, 2, 3])).toBeFalsy();
    expect(is.Infinity(new Array())).toBeFalsy();
    expect(is.Infinity({})).toBeFalsy();
    expect(is.Infinity({ key: 'value' })).toBeFalsy();
    expect(is.Infinity(new Object())).toBeFalsy();
    expect(is.Infinity(() => {})).toBeFalsy();
    expect(is.Infinity(function () {})).toBeFalsy();
    expect(is.Infinity(new Function())).toBeFalsy();
    expect(is.Infinity(undefined)).toBeFalsy();
    expect(is.Infinity(null)).toBeFalsy();
    expect(is.Infinity(NaN)).toBeFalsy();
    expect(is.Infinity(new Number(NaN))).toBeFalsy();
    expect(is.Infinity(Infinity)).toBeTruthy();
    expect(is.Infinity(-Infinity)).toBeTruthy();
    expect(is.Infinity(new Number(Infinity))).toBeTruthy();
  });

  describe('not', () => {
    test('boolean()', () => {
      expect(is.not.boolean(false)).toBeFalsy();
      expect(is.not.boolean(true)).toBeFalsy();
      expect(is.not.boolean(new Boolean())).toBeFalsy();
      expect(is.not.boolean(0)).toBeTruthy();
      expect(is.not.boolean(1)).toBeTruthy();
      expect(is.not.boolean(new Number())).toBeTruthy();
      expect(is.not.boolean('')).toBeTruthy();
      expect(is.not.boolean('test')).toBeTruthy();
      expect(is.not.boolean(new String('Test'))).toBeTruthy();
      expect(is.not.boolean([])).toBeTruthy();
      expect(is.not.boolean([1, 2, 3])).toBeTruthy();
      expect(is.not.boolean(new Array())).toBeTruthy();
      expect(is.not.boolean({})).toBeTruthy();
      expect(is.not.boolean({ key: 'value' })).toBeTruthy();
      expect(is.not.boolean(new Object())).toBeTruthy();
      expect(is.not.boolean(() => {})).toBeTruthy();
      expect(is.not.boolean(function () {})).toBeTruthy();
      expect(is.not.boolean(new Function())).toBeTruthy();
      expect(is.not.boolean(undefined)).toBeTruthy();
      expect(is.not.boolean(null)).toBeTruthy();
      expect(is.not.boolean(NaN)).toBeTruthy();
      expect(is.not.boolean(new Number(NaN))).toBeTruthy();
      expect(is.not.boolean(Infinity)).toBeTruthy();
      expect(is.not.boolean(-Infinity)).toBeTruthy();
      expect(is.not.boolean(new Number(Infinity))).toBeTruthy();
    });
    test('number()', () => {
      expect(is.not.number(false)).toBeTruthy();
      expect(is.not.number(true)).toBeTruthy();
      expect(is.not.number(new Boolean())).toBeTruthy();
      expect(is.not.number(0)).toBeFalsy();
      expect(is.not.number(1)).toBeFalsy();
      expect(is.not.number(new Number())).toBeFalsy();
      expect(is.not.number('')).toBeTruthy();
      expect(is.not.number('test')).toBeTruthy();
      expect(is.not.number(new String('Test'))).toBeTruthy();
      expect(is.not.number([])).toBeTruthy();
      expect(is.not.number([1, 2, 3])).toBeTruthy();
      expect(is.not.number(new Array())).toBeTruthy();
      expect(is.not.number({})).toBeTruthy();
      expect(is.not.number({ key: 'value' })).toBeTruthy();
      expect(is.not.number(new Object())).toBeTruthy();
      expect(is.not.number(() => {})).toBeTruthy();
      expect(is.not.number(function () {})).toBeTruthy();
      expect(is.not.number(new Function())).toBeTruthy();
      expect(is.not.number(undefined)).toBeTruthy();
      expect(is.not.number(null)).toBeTruthy();
      expect(is.not.number(NaN)).toBeTruthy();
      expect(is.not.number(new Number(NaN))).toBeTruthy();
      expect(is.not.number(Infinity)).toBeTruthy();
      expect(is.not.number(-Infinity)).toBeTruthy();
      expect(is.not.number(new Number(Infinity))).toBeTruthy();
    });
    test('string()', () => {
      expect(is.not.string(false)).toBeTruthy();
      expect(is.not.string(true)).toBeTruthy();
      expect(is.not.string(new Boolean())).toBeTruthy();
      expect(is.not.string(0)).toBeTruthy();
      expect(is.not.string(1)).toBeTruthy();
      expect(is.not.string(new Number())).toBeTruthy();
      expect(is.not.string('')).toBeFalsy();
      expect(is.not.string('test')).toBeFalsy();
      expect(is.not.string(new String('Test'))).toBeFalsy();
      expect(is.not.string([])).toBeTruthy();
      expect(is.not.string([1, 2, 3])).toBeTruthy();
      expect(is.not.string(new Array())).toBeTruthy();
      expect(is.not.string({})).toBeTruthy();
      expect(is.not.string({ key: 'value' })).toBeTruthy();
      expect(is.not.string(new Object())).toBeTruthy();
      expect(is.not.string(() => {})).toBeTruthy();
      expect(is.not.string(function () {})).toBeTruthy();
      expect(is.not.string(new Function())).toBeTruthy();
      expect(is.not.string(undefined)).toBeTruthy();
      expect(is.not.string(null)).toBeTruthy();
      expect(is.not.string(NaN)).toBeTruthy();
      expect(is.not.string(new Number(NaN))).toBeTruthy();
      expect(is.not.string(Infinity)).toBeTruthy();
      expect(is.not.string(-Infinity)).toBeTruthy();
      expect(is.not.string(new Number(Infinity))).toBeTruthy();
    });
    test('array()', () => {
      expect(is.not.array(false)).toBeTruthy();
      expect(is.not.array(true)).toBeTruthy();
      expect(is.not.array(new Boolean())).toBeTruthy();
      expect(is.not.array(0)).toBeTruthy();
      expect(is.not.array(1)).toBeTruthy();
      expect(is.not.array(new Number())).toBeTruthy();
      expect(is.not.array('')).toBeTruthy();
      expect(is.not.array('test')).toBeTruthy();
      expect(is.not.array(new String('Test'))).toBeTruthy();
      expect(is.not.array([])).toBeFalsy();
      expect(is.not.array([1, 2, 3])).toBeFalsy();
      expect(is.not.array(new Array())).toBeFalsy();
      expect(is.not.array({})).toBeTruthy();
      expect(is.not.array({ key: 'value' })).toBeTruthy();
      expect(is.not.array(new Object())).toBeTruthy();
      expect(is.not.array(() => {})).toBeTruthy();
      expect(is.not.array(function () {})).toBeTruthy();
      expect(is.not.array(new Function())).toBeTruthy();
      expect(is.not.array(undefined)).toBeTruthy();
      expect(is.not.array(null)).toBeTruthy();
      expect(is.not.array(NaN)).toBeTruthy();
      expect(is.not.array(new Number(NaN))).toBeTruthy();
      expect(is.not.array(Infinity)).toBeTruthy();
      expect(is.not.array(-Infinity)).toBeTruthy();
      expect(is.not.array(new Number(Infinity))).toBeTruthy();
    });
    test('object()', () => {
      expect(is.not.object(false)).toBeTruthy();
      expect(is.not.object(true)).toBeTruthy();
      expect(is.not.object(new Boolean())).toBeTruthy();
      expect(is.not.object(0)).toBeTruthy();
      expect(is.not.object(1)).toBeTruthy();
      expect(is.not.object(new Number())).toBeTruthy();
      expect(is.not.object('')).toBeTruthy();
      expect(is.not.object('test')).toBeTruthy();
      expect(is.not.object(new String('Test'))).toBeTruthy();
      expect(is.not.object([])).toBeTruthy();
      expect(is.not.object([1, 2, 3])).toBeTruthy();
      expect(is.not.object(new Array())).toBeTruthy();
      expect(is.not.object({})).toBeFalsy();
      expect(is.not.object({ key: 'value' })).toBeFalsy();
      expect(is.not.object(new Object())).toBeFalsy();
      expect(is.not.object(() => {})).toBeTruthy();
      expect(is.not.object(function () {})).toBeTruthy();
      expect(is.not.object(new Function())).toBeTruthy();
      expect(is.not.object(undefined)).toBeTruthy();
      expect(is.not.object(null)).toBeTruthy();
      expect(is.not.object(NaN)).toBeTruthy();
      expect(is.not.object(new Number(NaN))).toBeTruthy();
      expect(is.not.object(Infinity)).toBeTruthy();
      expect(is.not.object(-Infinity)).toBeTruthy();
      expect(is.not.object(new Number(Infinity))).toBeTruthy();
    });
    test('function()', () => {
      expect(is.not.function(false)).toBeTruthy();
      expect(is.not.function(true)).toBeTruthy();
      expect(is.not.function(new Boolean())).toBeTruthy();
      expect(is.not.function(0)).toBeTruthy();
      expect(is.not.function(1)).toBeTruthy();
      expect(is.not.function(new Number())).toBeTruthy();
      expect(is.not.function('')).toBeTruthy();
      expect(is.not.function('test')).toBeTruthy();
      expect(is.not.function(new String('Test'))).toBeTruthy();
      expect(is.not.function([])).toBeTruthy();
      expect(is.not.function([1, 2, 3])).toBeTruthy();
      expect(is.not.function(new Array())).toBeTruthy();
      expect(is.not.function({})).toBeTruthy();
      expect(is.not.function({ key: 'value' })).toBeTruthy();
      expect(is.not.function(new Object())).toBeTruthy();
      expect(is.not.function(() => {})).toBeFalsy();
      expect(is.not.function(function () {})).toBeFalsy();
      expect(is.not.function(new Function())).toBeFalsy();
      expect(is.not.function(undefined)).toBeTruthy();
      expect(is.not.function(null)).toBeTruthy();
      expect(is.not.function(NaN)).toBeTruthy();
      expect(is.not.function(new Number(NaN))).toBeTruthy();
      expect(is.not.function(Infinity)).toBeTruthy();
      expect(is.not.function(-Infinity)).toBeTruthy();
      expect(is.not.function(new Number(Infinity))).toBeTruthy();
    });

    test('undefined()', () => {
      expect(is.not.undefined(false)).toBeTruthy();
      expect(is.not.undefined(true)).toBeTruthy();
      expect(is.not.undefined(new Boolean())).toBeTruthy();
      expect(is.not.undefined(0)).toBeTruthy();
      expect(is.not.undefined(1)).toBeTruthy();
      expect(is.not.undefined(new Number())).toBeTruthy();
      expect(is.not.undefined('')).toBeTruthy();
      expect(is.not.undefined('test')).toBeTruthy();
      expect(is.not.undefined(new String('Test'))).toBeTruthy();
      expect(is.not.undefined([])).toBeTruthy();
      expect(is.not.undefined([1, 2, 3])).toBeTruthy();
      expect(is.not.undefined(new Array())).toBeTruthy();
      expect(is.not.undefined({})).toBeTruthy();
      expect(is.not.undefined({ key: 'value' })).toBeTruthy();
      expect(is.not.undefined(new Object())).toBeTruthy();
      expect(is.not.undefined(() => {})).toBeTruthy();
      expect(is.not.undefined(function () {})).toBeTruthy();
      expect(is.not.undefined(new Function())).toBeTruthy();
      expect(is.not.undefined(undefined)).toBeFalsy();
      expect(is.not.undefined(null)).toBeTruthy();
      expect(is.not.undefined(NaN)).toBeTruthy();
      expect(is.not.undefined(new Number(NaN))).toBeTruthy();
      expect(is.not.undefined(Infinity)).toBeTruthy();
      expect(is.not.undefined(-Infinity)).toBeTruthy();
      expect(is.not.undefined(new Number(Infinity))).toBeTruthy();
    });
    test('null()', () => {
      expect(is.not.null(false)).toBeTruthy();
      expect(is.not.null(true)).toBeTruthy();
      expect(is.not.null(new Boolean())).toBeTruthy();
      expect(is.not.null(0)).toBeTruthy();
      expect(is.not.null(1)).toBeTruthy();
      expect(is.not.null(new Number())).toBeTruthy();
      expect(is.not.null('')).toBeTruthy();
      expect(is.not.null('test')).toBeTruthy();
      expect(is.not.null(new String('Test'))).toBeTruthy();
      expect(is.not.null([])).toBeTruthy();
      expect(is.not.null([1, 2, 3])).toBeTruthy();
      expect(is.not.null(new Array())).toBeTruthy();
      expect(is.not.null({})).toBeTruthy();
      expect(is.not.null({ key: 'value' })).toBeTruthy();
      expect(is.not.null(new Object())).toBeTruthy();
      expect(is.not.null(() => {})).toBeTruthy();
      expect(is.not.null(function () {})).toBeTruthy();
      expect(is.not.null(new Function())).toBeTruthy();
      expect(is.not.null(undefined)).toBeTruthy();
      expect(is.not.null(null)).toBeFalsy();
      expect(is.not.null(NaN)).toBeTruthy();
      expect(is.not.null(new Number(NaN))).toBeTruthy();
      expect(is.not.null(Infinity)).toBeTruthy();
      expect(is.not.null(-Infinity)).toBeTruthy();
      expect(is.not.null(new Number(Infinity))).toBeTruthy();
    });
    test('NaN()', () => {
      expect(is.not.NaN(false)).toBeTruthy();
      expect(is.not.NaN(true)).toBeTruthy();
      expect(is.not.NaN(new Boolean())).toBeTruthy();
      expect(is.not.NaN(0)).toBeTruthy();
      expect(is.not.NaN(1)).toBeTruthy();
      expect(is.not.NaN(new Number())).toBeTruthy();
      expect(is.not.NaN('')).toBeTruthy();
      expect(is.not.NaN('test')).toBeTruthy();
      expect(is.not.NaN(new String('Test'))).toBeTruthy();
      expect(is.not.NaN([])).toBeTruthy();
      expect(is.not.NaN([1, 2, 3])).toBeTruthy();
      expect(is.not.NaN(new Array())).toBeTruthy();
      expect(is.not.NaN({})).toBeTruthy();
      expect(is.not.NaN({ key: 'value' })).toBeTruthy();
      expect(is.not.NaN(new Object())).toBeTruthy();
      expect(is.not.NaN(() => {})).toBeTruthy();
      expect(is.not.NaN(function () {})).toBeTruthy();
      expect(is.not.NaN(new Function())).toBeTruthy();
      expect(is.not.NaN(undefined)).toBeTruthy();
      expect(is.not.NaN(null)).toBeTruthy();
      expect(is.not.NaN(NaN)).toBeFalsy();
      expect(is.not.NaN(new Number(NaN))).toBeFalsy();
      expect(is.not.NaN(Infinity)).toBeTruthy();
      expect(is.not.NaN(-Infinity)).toBeTruthy();
      expect(is.not.NaN(new Number(Infinity))).toBeTruthy();
    });
    test('Infinity()', () => {
      expect(is.not.Infinity(false)).toBeTruthy();
      expect(is.not.Infinity(true)).toBeTruthy();
      expect(is.not.Infinity(new Boolean())).toBeTruthy();
      expect(is.not.Infinity(0)).toBeTruthy();
      expect(is.not.Infinity(1)).toBeTruthy();
      expect(is.not.Infinity(new Number())).toBeTruthy();
      expect(is.not.Infinity('')).toBeTruthy();
      expect(is.not.Infinity('test')).toBeTruthy();
      expect(is.not.Infinity(new String('Test'))).toBeTruthy();
      expect(is.not.Infinity([])).toBeTruthy();
      expect(is.not.Infinity([1, 2, 3])).toBeTruthy();
      expect(is.not.Infinity(new Array())).toBeTruthy();
      expect(is.not.Infinity({})).toBeTruthy();
      expect(is.not.Infinity({ key: 'value' })).toBeTruthy();
      expect(is.not.Infinity(new Object())).toBeTruthy();
      expect(is.not.Infinity(() => {})).toBeTruthy();
      expect(is.not.Infinity(function () {})).toBeTruthy();
      expect(is.not.Infinity(new Function())).toBeTruthy();
      expect(is.not.Infinity(undefined)).toBeTruthy();
      expect(is.not.Infinity(null)).toBeTruthy();
      expect(is.not.Infinity(NaN)).toBeTruthy();
      expect(is.not.Infinity(new Number(NaN))).toBeTruthy();
      expect(is.not.Infinity(Infinity)).toBeFalsy();
      expect(is.not.Infinity(-Infinity)).toBeFalsy();
      expect(is.not.Infinity(new Number(Infinity))).toBeFalsy();
    });
  });
});
